name: APK-J2 Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: q215613905
            repoUrl: https://github.com/q215613905/TVBoxOS
            branchName: main
          - userName: takagen99
            repoUrl: https://github.com/takagen99/Box
            branchName: main 
    env:
      local_xwalk: ${{ secrets.LOCAL_XWALK }}
      # 登录蓝奏云后在控制台运行document.cookie
      ylogin: ${{ secrets.YLOGIN }}
      phpdisk_info: ${{ secrets.PHPDISK_INFO }}
      # 蓝奏云里的文件夹ID（TVBoxOS:5848262）
      lanzou_folder_id: 5889934 
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Project
        run: git clone -b main --depth=1 https://github.com/q215613905/TVBoxOS.git
      - name: DIY
        run: |
          chmod +x diy-J.sh
          bash ${{ github.workspace }}/diy-J.sh
      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew  | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew  | cut -d \/ -f$num)
          cd $DIR
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
          
      - name: Upload App To Lanzou
        if: ${{ env.commit && env.ylogin }}
        run: |
          python3 ${{ github.workspace }}/actions/.github/scripts/lzy_web.py \
          "${{ github.workspace }}/TVBoxOSC/apk/TVBox_${{ matrix.userName }}_${{ env.tag }}.apk" "$lanzou_folder_id"
          echo "share address: https://wws.lanzouv.com/b03pbjwof password:TVBox